name: Python versions test
on:
  [push, workflow_dispatch]

jobs:
  test_python_versions:
    name: Python versions test
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependency
      run: pip install nox[pbs]

    - name: Checkout Last Commit
      uses: actions/checkout@v6

    - name: Run Nox
      run: |
        nox
        echo ${{ GITHUB_STEP_SUMMARY }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ./*.xml
