name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment:
    name: Make comment to a chat
    runs-on: ubuntu-latest

    steps:
    - name: Comment new PR
      if: |
        github.event == "pull_request" &&
        contains(fromJSON('["opened", "reopened"]'), github.event.pull_request.type)
      run: echo A PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}

    - name: Comment new comment
      if: |
        github.event == "issue_comment" &&
        github.event.issue.pull_request
      run: echo A comment on PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}
