name: Telegram bot
on:
  pull_request:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]
  workflow_run:
    workflows: [Universum check]
    types: [completed]
    
jobs:
  make-comment:
    name: Send comment to TG
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_BASE: ${{ github.event.pull_request.base.ref }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_MERGED: ${{ github.event.pull_request.merged_by.login }}
      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
      COMMENT_URL: ${{ github.event.comment.html_url }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMENT_NUMBER: ${{ github.event.issue.number }}
      UNIVERUM_COMMIT: ${{ github.event.workflow_run.head_sha }}
      UNIVERSUM_BRANCH: ${{ github.event.workflow_run.head_branch }}
      UNIVERSUM_LOG: ${{ github.event.workflow_run.html_url }}

    steps:
    - name: Send message to TG
      run: |
        if [[ ! -z "${{ github.event.pull_request }}" && "${{ github.event.action }}" == "opened" ]]; then
          TEXT=$NEW_PR
        elif [[ ! -z "${{ github.event.pull_request }}" && "${{ github.event.action }}" == "synchronize" ]]; then
          TEXT=$PR_UPDATE
        elif [[ ! -z "${{ github.event.pull_request }}" && "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
          TEXT=$PR_MERGED
        elif [[ ! -z "${{ github.event.comment }}" ]]; then
          TEXT=$NEW_COMMENT
        elif [[ ! -z "${{ github.event.workflow_run }}" && "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
          TEXT=$UNIVERSUM_SUCCEEDED
        elif [[ ! -z "${{ github.event.workflow_run }}" && "${{ github.event.workflow_run.conclusion }}" == "failure" ]]; then
          TEXT=$UNIVERSUM_FAILED
        fi
        if [[ ! -z $TEXT ]]; then
          curl --get --data-urlencode "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" --data-urlencode "text=$TEXT" $URL
        fi
      env:
        URL: https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
        NEW_PR: |
          ${{ env.PR_AUTHOR }} created new PR#${{ env.PR_NUMBER }} '${{ env.PR_NAME }}' to branch '${{ env.PR_BASE }}'.
          See here: ${{ env.PR_URL }}
        PR_UPDATE: |
          ${{ env.PR_AUTHOR }} updated PR#${{ env.PR_NUMBER }};
          see here: ${{ env.PR_URL }}
        PR_MERGED: |
          ${{ env.PR_MERGED }} merged PR#${{env.PR_NUMBER }} to branch '${{ env.PR_BASE }}'
        NEW_COMMENT: |
          ${{ env.COMMENT_AUTHOR }} posted the following comment to issue #${{ env.COMMENT_NUMBER }}:
          ${{ env.COMMENT_BODY }}
          See issue here: ${{ env.COMMENT_URL }}
        UNIVERSUM_SUCCEEDED: |
          Universum run for commit ${{ env.UNIVERUM_COMMIT }} for branch '${{ env.UNIVERSUM_BRANCH }}' succeeded.
          See log here: ${{ env.UNIVERSUM_LOG }}
        UNIVERSUM_FAILED: |
          Universum run for commit ${{ env.UNIVERUM_COMMIT }} for branch '${{ env.UNIVERSUM_BRANCH }}' failed.
          See log here: ${{ env.UNIVERSUM_LOG }}
