name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  make-comment:
    name: Send comment to TG
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_BASE: ${{ github.event.pull_request.base.ref }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
      COMMENT_URL: ${{ github.event.comment.html_url }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMENT_NUMBER: ${{ github.event.issue.number }}

    steps:
    - name: Comment new PR
      if: github.event.pull_request && github.event.action == 'opened'
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.PR_AUTHOR }} created new PR '${{ env.PR_NAME }}' to branch '${{ env.PR_BASE }}'.
          See here: ${{ env.PR_URL }}

    - name: Comment update PR
      if: github.event.pull_request && github.event.action == 'synchronize'
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.PR_AUTHOR }} updated PR ${{ env.PR_NUMBER }};
          see here: ${{ env.PR_URL }}

    - name: Comment new comment
      if: github.event.comment && github.event.action == 'created'
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.COMMENT_AUTHOR }} posted the following comment (${{ env.COMMENT_URL }}) to issue ${{ env.COMMENT_NUMBER }}:
          ${{ env.COMMENT_BODY }}

    - name: Send comment to TG
      if: env.TEXT
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${{ env.TEXT }}
